# Generated by Django 2.2.9 on 2020-01-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200121_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
